

text = 'CAGTTTTAGTAGCCACATCATTTAAACCTGGAGTTCGAGACCGAGTGACGGCTTTTCACGACGGATGGAATCACAGTATTAGTTCTATGATCCCTGTAACCAAGTTCAATCGTTCTGCATAACGAACCGGACTGCACTCAGGACGTAGGGGCGTTACTGCCGACCGCGGTGACATTCAGCGAACAACAGTTTCGTGCATGGGGACGTAGTCTAGGTGGCCCATTACGCACATCGTTCGATAGCGACCATGAGGACGCACGTAACTTAATACTCACTTTTGTTTAGTTCATTTATACAGCAAGAATGATGGCACGACGTACGTCGCACACATACGGTAGTTACGCGATATCTGAGTCGGTGTGATACCGATGGTGGAATCAAGGCTCCTACTCAACCTTTGCTTAACGTGTACAAGCTTCAAGTATCTTGGGCCGGCTAGGCCGTCGGCGGACCGATCTCCTCAAAGTAGGACCAGATCACGCATAGGGATGTTCCGGCAGTGGACTTCCACTAAGTAGGTCGAGCCAGAGGTGCAGACGTGAGTCCGTGAAAGATTATTACGATACTGACTATGATGCACACTCGGGTTACATTTCTGATCCTCCGTTAGAACCCATAATAGTACAACGCTGTTTTTTGTCCCACGTAATGCCCCGGGCAAGGCAAACGCCGAAGCGAAGATTCTCCACTTCTGTCGACACCCTCTTAAGTTATCAATCTTTGTGTTTCCATTGTATTCGGACTTCTCCAAGTAACCGTATAGCGGGATGGATTTCGTGCGGCACTAAGAACTGAAATTGTCTGTGAGCTGCCTCCTGGCCTAATACATTATTTGTTACTCTTAACTAGATATTGCACGGGACGGAAAGGCTCCGCGAGTCATCAAACCCGACTGCTATTGGCTGAGATCGGTATGACCGCGTGCACGAATACCTACACTCGGCGGAAACAACGGAGTGCATGCAGGTGGGCACGACACCAGAACCTGCCTGGAGAACTG'
k = 15

profile_matrix = []
with open('dataset_159_3.txt','r') as f:
    for line in f:
        line = line.strip()
        line = line.split(' ')
        profile_matrix.append(line)

def profile_most_probable(text, k, profile_matrix):
    base_index = ['A','C','G','T']
    pattern_list = []
    probable_list = []
    
    for i in range(len(text)-k+1):
        pattern = text[i:i+k]
        pattern_list.append(pattern)
        
        probable_sum = 1

        for j in range(k):
            base = pattern[j]
            base_nu = base_index.index(base)
            probable_sum = probable_sum*float(profile_matrix[base_nu][j])

        probable_list.append(probable_sum)

    max_probable = max(probable_list)
    max_probable_index = probable_list.index(max_probable)
    pattern = pattern_list[max_probable_index]

    return pattern

print(profile_most_probable(text, k, profile_matrix))


