
text = 'GCACTTCTCGTAGGTGACCATTCGCACTTCTGCACTTCTAACAGCGCCAACAGCGCCCGTAGGTGGCACTTCTCGTAGGTGACCATTCACCATTCCGTAGGTGAACAGCGCCAACAGCGCCCGTAGGTGCGTAGGTGACCATTCACCATTCAACAGCGCCATAGCATCAACAGCGCCGCACTTCTACCATTCCGTAGGTGCGTAGGTGCGTAGGTGATAGCATCACCATTCCGTAGGTGATAGCATCCGTAGGTGAACAGCGCCACCATTCATAGCATCATAGCATCGCACTTCTCGTAGGTGGCACTTCTATAGCATCCGTAGGTGATAGCATCAACAGCGCCATAGCATCGCACTTCTCGTAGGTGGCACTTCTCGTAGGTGATAGCATCAACAGCGCCATAGCATCCGTAGGTGCGTAGGTGACCATTCAACAGCGCCACCATTCAACAGCGCCATAGCATCATAGCATCAACAGCGCCAACAGCGCCATAGCATCATAGCATCACCATTCATAGCATCGCACTTCTATAGCATCATAGCATCAACAGCGCCCGTAGGTGACCATTCATAGCATCGCACTTCTCGTAGGTGACCATTCCGTAGGTGCGTAGGTGGCACTTCTATAGCATCCGTAGGTGACCATTCACCATTCATAGCATCGCACTTCTACCATTCAACAGCGCCACCATTCATAGCATCCGTAGGTGATAGCATCATAGCATCCGTAGGTGCGTAGGTGCGTAGGTGCGTAGGTGCGTAGGTGCGTAGGTGAACAGCGCCATAGCATCGCACTTCTAACAGCGCCATAGCATCATAGCATC'
k = 11

def pattern_count(text, pattern):
    count = 0
    for i in range(len(text) - len(pattern) + 1):
        if text[i : i+len(pattern)] == pattern:
            count = count + 1

    return count


def frequent_words(text, k):
    count = []
    frequent_pattern = set()
    for i in range(len(text) - k + 1):
        pattern = text[i : i + k]
        count.append(pattern_count(text, pattern))

    maxcount = max(count)
    #print(maxcount)

    for i in range(len(text) - k + 1):
        if count[i] == maxcount:
            frequent_pattern.add(text[i : i+k])

    for item in frequent_pattern:
        print(item)


frequent_words(text, k)


